### ISSUE TITLE
Readcheck bug with multiple nodes 

### ISSUE THREAD

**Issue by JulianKunkel** [IOR-LANL/ior#13]
There is a bug introduced by me in the readcheck patches.
I supplied a patch below problem with the outstanding merge request...

**Comment by JulianKunkel** [comment]
From d1efb6dc88a16bb5a42285a0c620d9d4a8c83c24 Mon Sep 17 00:00:00 2001
From: Julian Kunkel <juliankunkel@googlemail.com>
Date: Wed, 25 Oct 2017 14:58:11 +0200
Subject: [PATCH] Bugfix for readcheck with multiple nodes.

---
 src/ior.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/ior.c b/src/ior.c
index 5319a57..ebc2742 100755
--- a/src/ior.c
+++ b/src/ior.c
@@ -2145,7 +2145,7 @@ static void TestIoSys(IOR_test_t *test)
                                 }
                         }
                         if(operation_flag == READCHECK){
-                            FillBuffer(ioBuffers.readCheckBuffer, params, 0, rank + rankOffset);
+                            FillBuffer(ioBuffers.readCheckBuffer, params, 0, (rank + rankOffset) % params->numTasks);
                         }
 
                         /* Using globally passed rankOffset, following function generates testFileName to read */
-- 
2.7.4

**Comment by johnbent** [comment]
I patched this in.  Thanks Julian.
