### ISSUE TITLE
MDTest - Show FS Summary Function has uninitialized var

### ISSUE THREAD

**Issue by ahueck** [IOR-LANL/ior#28]
In the function **show_file_system_size** the variable **real_path[MAX_LEN];** is never initialized with useful data:
https://github.com/IOR-LANL/ior/blob/e6e0527d72face86a043b2b59cb87b066c44707b/src/mdtest.c#L1613

The subsequent print statement **fprintf(stdout, "Path: %s\n", real_path);** thus prints random characters:
https://github.com/IOR-LANL/ior/blob/e6e0527d72face86a043b2b59cb87b066c44707b/src/mdtest.c#L1659

In earlier versions, the following code was used (depending on preprocessor flags):
`
    if (realpath(file_system, real_path) == NULL) {
       FAIL("unable to use realpath()");
    }
`

The commit which removed the code was: https://github.com/IOR-LANL/ior/commit/0c9921dc0d1bf540e72177e5dd4c10beb9c3365e#diff-6693dc363a2f01ec84e299f65aa09a70

I would do a pull request with the aforementioned code, but I am not too sure about the availability of realpath on all systems which are supported by mdtest/ior.

**Comment by glennklockwood** [comment]
Thanks for catching this.  It looks like the PLFS removal patch (0c9921d) was a little overzealous.  `realpath` is part of POSIX so it should be available everywhere and should not have been removed.

If you have a patch that restores the functionality and works, could you submit a pull request?

**Comment by glennklockwood** [comment]
Thanks!  This looks great.  Did basic tests and all is well.

I'm not 100% clear on what would happen if one used a non-POSIX aiori with this code, but it will be no worse than whatever happened before the PLFS support was removed.
